
package com.ljwd.plms.web.wsdl.webservice.channelService;

import com.ljwd.plms.web.wsdl.webservice.WSDLBaseService;
import com.ljwd.plms.web.wsdl.webservice.exception.ErrorInfoException_Exception;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChannelService", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface ChannelService extends WSDLBaseService{

    /**
     * @param param
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addBookings", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddBookings")
    @ResponseWrapper(localName = "addBookingsResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddBookingsResponse")
    public void addBookings(
        @WebParam(name = "param", targetNamespace = "")
        List<BookingDto> param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchFuncTypeList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchFuncTypeList")
    @ResponseWrapper(localName = "searchFuncTypeListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchFuncTypeListResponse")
    public List<AppIdNameSearchResultDto> searchFuncTypeList()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addAnnex", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddAnnex")
    @ResponseWrapper(localName = "addAnnexResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddAnnexResponse")
    public void addAnnex(
        @WebParam(name = "annexDto", targetNamespace = "")
        ChAnnexDto annexDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLoanPeriod", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllLoanPeriod")
    @ResponseWrapper(localName = "getAllLoanPeriodResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllLoanPeriodResponse")
    public List<String> getAllLoanPeriod()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.SiteSearchResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchSiteList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchSiteList")
    @ResponseWrapper(localName = "searchSiteListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchSiteListResponse")
    public SiteSearchResultDto searchSiteList(
        @WebParam(name = "param", targetNamespace = "")
        SiteSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchProfLevelList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchProfLevelList")
    @ResponseWrapper(localName = "searchProfLevelListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchProfLevelListResponse")
    public List<AppIdNameSearchResultDto> searchProfLevelList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.LogoutResponse")
    public void logout()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param applInfoDto
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.MoonlightApplInfoResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMoonlightApplicationInfo", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddMoonlightApplicationInfo")
    @ResponseWrapper(localName = "addMoonlightApplicationInfoResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddMoonlightApplicationInfoResponse")
    public MoonlightApplInfoResultDto addMoonlightApplicationInfo(
        @WebParam(name = "applInfoDto", targetNamespace = "")
        MoonlightApplicationInfoDto applInfoDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.SiteSearchResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSiteListOnBranch", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetSiteListOnBranch")
    @ResponseWrapper(localName = "getSiteListOnBranchResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetSiteListOnBranchResponse")
    public SiteSearchResultDto getSiteListOnBranch()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param applInfoParamSyncDto
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.ChApplInfoListSyncDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncApplicationInfo", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncApplicationInfo")
    @ResponseWrapper(localName = "syncApplicationInfoResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncApplicationInfoResponse")
    public ChApplInfoListSyncDto syncApplicationInfo(
        @WebParam(name = "applInfoParamSyncDto", targetNamespace = "")
        ChApplInfoParamSyncDto applInfoParamSyncDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param employeeNo
     * @param oldPassword
     * @param password
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.ChangeUserPasswordResponse")
    public void changeUserPassword(
        @WebParam(name = "employeeNo", targetNamespace = "")
        String employeeNo,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "oldPassword", targetNamespace = "")
        String oldPassword)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionByNameList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionByNameList")
    @ResponseWrapper(localName = "searchAdminRegionByNameListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionByNameListResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionByNameList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param applicationId
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.MoonlightLoanStatusDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoonlightLoanStatus", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetMoonlightLoanStatus")
    @ResponseWrapper(localName = "getMoonlightLoanStatusResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetMoonlightLoanStatusResponse")
    public MoonlightLoanStatusDto getMoonlightLoanStatus(
        @WebParam(name = "applicationId", targetNamespace = "")
        long applicationId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.SiteRegionMapDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchSiteRegionMapList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchSiteRegionMapList")
    @ResponseWrapper(localName = "searchSiteRegionMapListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchSiteRegionMapListResponse")
    public List<SiteRegionMapDto> searchSiteRegionMapList(
        @WebParam(name = "param", targetNamespace = "")
        SiteRegionMapSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionCityList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionCityList")
    @ResponseWrapper(localName = "searchAdminRegionCityListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionCityListResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionCityList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchUnitNatureList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchUnitNatureList")
    @ResponseWrapper(localName = "searchUnitNatureListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchUnitNatureListResponse")
    public List<AppIdNameSearchResultDto> searchUnitNatureList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param employeeNo
     * @param password
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.UserProfileDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticateUser", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AuthenticateUser")
    @ResponseWrapper(localName = "authenticateUserResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AuthenticateUserResponse")
    public UserProfileDto authenticateUser(
        @WebParam(name = "employeeNo", targetNamespace = "")
        String employeeNo,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchIndustryTypeList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchIndustryTypeList")
    @ResponseWrapper(localName = "searchIndustryTypeListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchIndustryTypeListResponse")
    public List<AppIdNameSearchResultDto> searchIndustryTypeList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.ProductDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllProductsResponse")
    public List<ProductDto> getAllProducts()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param applId
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.ApplicationInfoApplyProgressResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationInfoApplyProgress", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetApplicationInfoApplyProgress")
    @ResponseWrapper(localName = "getApplicationInfoApplyProgressResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetApplicationInfoApplyProgressResponse")
    public ApplicationInfoApplyProgressResultDto getApplicationInfoApplyProgress(
        @WebParam(name = "applId", targetNamespace = "")
        long applId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.CompanyCustomerInfoSearchResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchCompanyCustomerInfo", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchCompanyCustomerInfo")
    @ResponseWrapper(localName = "searchCompanyCustomerInfoResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchCompanyCustomerInfoResponse")
    public CompanyCustomerInfoSearchResultDto searchCompanyCustomerInfo(
        @WebParam(name = "param", targetNamespace = "")
        CompanyCustomerInfoSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param syncParamDto
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.ChUserListSyncDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncUser", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncUser")
    @ResponseWrapper(localName = "syncUserResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncUserResponse")
    public ChUserListSyncDto syncUser(
        @WebParam(name = "syncParamDto", targetNamespace = "")
        ChDataSyncParamDto syncParamDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionAreaList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionAreaList")
    @ResponseWrapper(localName = "searchAdminRegionAreaListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionAreaListResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionAreaList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param applicationInfoDto
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.ChApplInfoResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addApplicationInfo", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddApplicationInfo")
    @ResponseWrapper(localName = "addApplicationInfoResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.AddApplicationInfoResponse")
    public ChApplInfoResultDto addApplicationInfo(
        @WebParam(name = "applicationInfoDto", targetNamespace = "")
        ChApplInfoDto applicationInfoDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param lovType
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.CommonLovDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLovList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetLovList")
    @ResponseWrapper(localName = "getLovListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetLovListResponse")
    public List<CommonLovDto> getLovList(
        @WebParam(name = "lovType", targetNamespace = "")
        LovType lovType)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.OrderFeedbackDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIntradayOrderFeedback", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetIntradayOrderFeedback")
    @ResponseWrapper(localName = "getIntradayOrderFeedbackResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetIntradayOrderFeedbackResponse")
    public List<OrderFeedbackDto> getIntradayOrderFeedback()
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.PaymentTypeDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPaymentType", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllPaymentType")
    @ResponseWrapper(localName = "getAllPaymentTypeResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.GetAllPaymentTypeResponse")
    public List<PaymentTypeDto> getAllPaymentType()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionByParam", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionByParam")
    @ResponseWrapper(localName = "searchAdminRegionByParamResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionByParamResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionByParam(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param userId
     * @return
     *     returns java.lang.String
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPwdByUserID", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchPwdByUserID")
    @ResponseWrapper(localName = "searchPwdByUserIDResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchPwdByUserIDResponse")
    public String searchPwdByUserID(
        @WebParam(name = "userId", targetNamespace = "")
        String userId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionZipList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionZipList")
    @ResponseWrapper(localName = "searchAdminRegionZipListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionZipListResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionZipList(
        @WebParam(name = "param", targetNamespace = "")
        AppIdNameSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAdminRegionProvinceList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionProvinceList")
    @ResponseWrapper(localName = "searchAdminRegionProvinceListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchAdminRegionProvinceListResponse")
    public List<AppIdNameSearchResultDto> searchAdminRegionProvinceList()
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.channelService.AppIdNameSearchResultDto>
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchEnterpriseTypeList", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchEnterpriseTypeList")
    @ResponseWrapper(localName = "searchEnterpriseTypeListResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchEnterpriseTypeListResponse")
    public List<AppIdNameSearchResultDto> searchEnterpriseTypeList()
        throws ErrorInfoException_Exception
    ;

    /**
     * @param syncParamDto
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.channelService.ChOrganizationListSyncDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncOrganization", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncOrganization")
    @ResponseWrapper(localName = "syncOrganizationResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SyncOrganizationResponse")
    public ChOrganizationListSyncDto syncOrganization(
        @WebParam(name = "syncParamDto", targetNamespace = "")
        ChDataSyncParamDto syncParamDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @return
     *     returns java.lang.String
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchReprotUrlByParam", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchReprotUrlByParam")
    @ResponseWrapper(localName = "searchReprotUrlByParamResponse", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.channelService.SearchReprotUrlByParamResponse")
    public String searchReprotUrlByParam()
        throws ErrorInfoException_Exception
    ;

}
