
package com.ljwd.plms.web.wsdl.webservice.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrorInfoException", targetNamespace = "http://webservice.loan.mfbms.flinkmf.com/")
public class ErrorInfoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorInfoException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ErrorInfoException_Exception(String message, ErrorInfoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ErrorInfoException_Exception(String message, ErrorInfoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ljwd.plms.web.wsdl.webservice.service.ErrorInfoException
     */
    public ErrorInfoException getFaultInfo() {
        return faultInfo;
    }

}
