
package com.ljwd.plms.web.wsdl.webservice.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MicroLoanInterface", targetNamespace = "http://internal.juxinli.webservice.club.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MicroLoanInterface {


    /**
     * 
     * @param idCardNo
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isQueryJxlByIdCardNo", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.IsQueryJxlByIdCardNo")
    @ResponseWrapper(localName = "isQueryJxlByIdCardNoResponse", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.IsQueryJxlByIdCardNoResponse")
    public boolean isQueryJxlByIdCardNo(
        @WebParam(name = "idCardNo", targetNamespace = "")
        String idCardNo);

    /**
     * 
     * @param applyId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isQueryJxl", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.IsQueryJxl")
    @ResponseWrapper(localName = "isQueryJxlResponse", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.IsQueryJxlResponse")
    public boolean isQueryJxl(
        @WebParam(name = "applyId", targetNamespace = "")
        Long applyId);

    /**
     * 
     * @param applyId
     * @return
     *     returns java.util.List<com.ljwd.plms.web.wsdl.webservice.service.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryContact10", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.QueryContact10")
    @ResponseWrapper(localName = "queryContact10Response", targetNamespace = "http://internal.juxinli.webservice.club.com/", className = "com.ljwd.plms.web.wsdl.webservice.service.QueryContact10Response")
    public List<Contact> queryContact10(
        @WebParam(name = "applyId", targetNamespace = "")
        Long applyId);

}
