
package com.ljwd.plms.web.wsdl.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MicroLoanInterfaceImplService", targetNamespace = "http://internal.juxinli.webservice.club.com/", wsdlLocation = "http://192.168.11.114/services/wsml?wsdl")
public class MicroLoanInterfaceImplService
    extends Service
{

    private final static URL MICROLOANINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MICROLOANINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName MICROLOANINTERFACEIMPLSERVICE_QNAME = new QName("http://internal.juxinli.webservice.club.com/", "MicroLoanInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.11.114/services/wsml?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MICROLOANINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        MICROLOANINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public MicroLoanInterfaceImplService() {
        super(__getWsdlLocation(), MICROLOANINTERFACEIMPLSERVICE_QNAME);
    }

    public MicroLoanInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MICROLOANINTERFACEIMPLSERVICE_QNAME, features);
    }

    public MicroLoanInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, MICROLOANINTERFACEIMPLSERVICE_QNAME);
    }

    public MicroLoanInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MICROLOANINTERFACEIMPLSERVICE_QNAME, features);
    }

    public MicroLoanInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MicroLoanInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MicroLoanInterface
     */
    @WebEndpoint(name = "MicroLoanInterfaceImplPort")
    public MicroLoanInterface getMicroLoanInterfaceImplPort() {
        return super.getPort(new QName("http://internal.juxinli.webservice.club.com/", "MicroLoanInterfaceImplPort"), MicroLoanInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MicroLoanInterface
     */
    @WebEndpoint(name = "MicroLoanInterfaceImplPort")
    public MicroLoanInterface getMicroLoanInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://internal.juxinli.webservice.club.com/", "MicroLoanInterfaceImplPort"), MicroLoanInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MICROLOANINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw MICROLOANINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return MICROLOANINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
