
package com.ljwd.plms.web.wsdl.webservice.annexService;

import com.ljwd.plms.web.wsdl.webservice.WSDLBaseService;
import com.ljwd.plms.web.wsdl.webservice.exception.ErrorInfoException_Exception;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "AnnexService", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface AnnexService extends WSDLBaseService {

    /**
     * @param backupIds
     * @param applicationCode
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addAnnexByExtractForBackup", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnexByExtractForBackup")
    @ResponseWrapper(localName = "addAnnexByExtractForBackupResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnexByExtractForBackupResponse")
    public void addAnnexByExtractForBackup(
            @WebParam(name = "applicationCode", targetNamespace = "")
            String applicationCode,
            @WebParam(name = "backupIds", targetNamespace = "")
            String backupIds)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexId
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.AnnexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadAnnex", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnex")
    @ResponseWrapper(localName = "downloadAnnexResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnexResponse")
    public AnnexDto downloadAnnex(
            @WebParam(name = "annexId", targetNamespace = "")
            long annexId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexId
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.AnnexBackupDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadAnnexBackupMtom", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnexBackupMtom")
    @ResponseWrapper(localName = "downloadAnnexBackupMtomResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnexBackupMtomResponse")
    public AnnexBackupDto downloadAnnexBackupMtom(
            @WebParam(name = "annexId", targetNamespace = "")
            long annexId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexId
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.AnnexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadAnnexMtom", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnexMtom")
    @ResponseWrapper(localName = "downloadAnnexMtomResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DownloadAnnexMtomResponse")
    public AnnexDto downloadAnnexMtom(
            @WebParam(name = "annexId", targetNamespace = "")
            long annexId)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.AnnexBackupSearchResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAnnexBackupList", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.SearchAnnexBackupList")
    @ResponseWrapper(localName = "searchAnnexBackupListResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.SearchAnnexBackupListResponse")
    public AnnexBackupSearchResultDto searchAnnexBackupList(
            @WebParam(name = "param", targetNamespace = "")
            AnnexBackupSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addAnnexMtom", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnexMtom")
    @ResponseWrapper(localName = "addAnnexMtomResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnexMtomResponse")
    public void addAnnexMtom(
            @WebParam(name = "annexDto", targetNamespace = "")
            AnnexDto annexDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.BocTradeQueryItemDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadBocFiles", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.UploadBocFiles")
    @ResponseWrapper(localName = "uploadBocFilesResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.UploadBocFilesResponse")
    public BocTradeQueryItemDto uploadBocFiles(
            @WebParam(name = "param", targetNamespace = "")
            BocUploadFilesParamDto param)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAnnex", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DeleteAnnex")
    @ResponseWrapper(localName = "deleteAnnexResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.DeleteAnnexResponse")
    public void deleteAnnex(
            @WebParam(name = "annexDto", targetNamespace = "")
            AnnexDto annexDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param annexDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addAnnex", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnex")
    @ResponseWrapper(localName = "addAnnexResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.AddAnnexResponse")
    public void addAnnex(
            @WebParam(name = "annexDto", targetNamespace = "")
            AnnexDto annexDto)
        throws ErrorInfoException_Exception
    ;

    /**
     * @param param
     * @return
     *     returns com.ljwd.plms.web.wsdl.webservice.annexService.AnnexSearchResultDto
     * @throws ErrorInfoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchAnnexList", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.SearchAnnexList")
    @ResponseWrapper(localName = "searchAnnexListResponse", targetNamespace = "http://webservice.annex.mfbms.flinkmf.com/", className = "com.ljwd.plms.web.wsdl.webservice.annexService.SearchAnnexListResponse")
    public AnnexSearchResultDto searchAnnexList(
            @WebParam(name = "param", targetNamespace = "")
            AnnexSearchParamDto param)
        throws ErrorInfoException_Exception
    ;

}
